image: docker:18.01.0-ce-git

variables:
  DOCKER_DRIVER: overlay
  INTERNAL_DOCKER_REGISTRY: "gitlab:5000"
  DOCKER_IMAGE: "gorest"
  CONTAINER_NAME: "gorest"
  REPO_NAME: tdlabs/gorest

services:
  - docker:dind

stages:
  - build
  - test
  - package
  - deploy

# see https://stackoverflow.com/questions/45537023/gitlab-ci-cache-keep-golang-packages-between-stages
before_script:
# see available variables: https://docs.gitlab.com/ce/ci/variables/README.html
  - 'echo -e "CI_BUILD_REF: $CI_BUILD_REF\nCI_PROJECT_DIR: $CI_PROJECT_DIR\nCI_PROJECT_NAMESPACE: $CI_PROJECT_NAMESPACE\nCI_PROJECT_NAME: $CI_PROJECT_NAME\nCI_PIPELINE_ID: $CI_PIPELINE_ID\n"'
  - 'cp -R _GO $GOPATH'

after_script:
  - 'cp -R $GOPATH ./_GO || :'

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - _GO/

build:go:
  stage: build
  image: golang:1.9.4
  script:
    - echo "preparing go env"
    - mkdir -p $GOPATH/src/github.com/thomasdarimont/gotraining
    - ln -sf $CI_PROJECT_DIR $GOPATH/src/github.com/thomasdarimont/gotraining
    - cd $GOPATH/src/github.com/thomasdarimont/gotraining/$CI_PROJECT_NAME
    - echo "bulding $CI_PROJECT_NAME..."
    - echo $(cat VERSION).$CI_PIPELINE_ID > VERSION
    - ./build.sh
  artifacts:
    paths:
      - out/*
      - vendor

test:go:
  stage: test
  image: golang:1.9.4
  script:
    - echo "running tests..."
    - go test ./...
    - echo "tests completed."
  dependencies:
    - build:go

package:docker:
  stage: package
  script:
    - echo "docker build..."
    - docker build -t $INTERNAL_DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA .
    - echo "docker build complete"
    - echo "docker push..."
    - docker push $INTERNAL_DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA
    - echo "docker image push complete"
  dependencies:
    - test:go

deploy:test:
  stage: deploy
  image: phusion/baseimage:0.10.0
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - 'mkdir -p ~/.ssh && chmod 700 ~/.ssh'
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
    - echo "Deploy to TEST environment"
    - ssh vagrant@test "docker stop $CONTAINER_NAME || true"
    - ssh vagrant@test "docker rm $CONTAINER_NAME || true"
    - ssh vagrant@test docker run -d --rm --name $CONTAINER_NAME -p 8090:8080 $INTERNAL_DOCKER_REGISTRY/$CONTAINER_NAME:$CI_COMMIT_SHA
  environment:
    name: test
    url: http://test:8090/
  dependencies:
  - package:docker
  only:
  - master

deploy:prod:
  stage: deploy
  image: phusion/baseimage:0.10.0
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - 'mkdir -p ~/.ssh && chmod 700 ~/.ssh'
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
    - echo "Deploy to PROD environment"
    - ssh vagrant@prod "docker stop $CONTAINER_NAME || true"
    - ssh vagrant@prod "docker rm $CONTAINER_NAME || true"
    - ssh vagrant@prod docker run -d --rm --name $CONTAINER_NAME -p 8090:8080 $INTERNAL_DOCKER_REGISTRY/$CONTAINER_NAME:$CI_COMMIT_SHA
  environment:
    name: prod
    url: http://prod:8090/
  dependencies:
  - package:docker
  when: manual
  only:
  - master