image: docker:18.01.0-ce-git

variables:
  DOCKER_DRIVER: overlay
  INTERNAL_DOCKER_REGISTRY: "gitlab:5000"
  DOCKER_IMAGE: "gorest"
  CONTAINER_NAME: "gorest"
  REPO_NAME: tdlabs/gorest

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

before_script:
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

build:go:
  stage: build
  image: golang:1.9.3-stretch
  script:
    - echo "Preparing go env"
    - mkdir -p $GOPATH/src/gitlab/$CI_PROJECT_NAMESPACE
    - ln -sf $CI_PROJECT_DIR $GOPATH/src/gitlab/$CI_PROJECT_NAMESPACE
    - cd $GOPATH/src/gitlab/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - go get -u github.com/golang/dep/cmd/dep
    - go get -u github.com/ahmetb/govvv

    - echo "Fetching dependencies..."
    - dep ensure

    - echo "Bulding gorest..."
    - CGO_ENABLED=0 GOOS=linux govvv build -o out/app
  artifacts:
    paths:
      - out/*
      - vendor

package:docker:
  stage: package
  script:
    - docker build -t $INTERNAL_DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $INTERNAL_DOCKER_REGISTRY/$DOCKER_IMAGE:$CI_COMMIT_SHA
    - echo "Build complete"
  dependencies:
    - build:go

deploy:test:
  stage: deploy
  image: ubuntu:17.10
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - 'mkdir -p ~/.ssh && chmod 700 ~/.ssh'
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  script:
    - echo "Deploy to TEST environment"
    - ssh vagrant@test "docker stop $CONTAINER_NAME || true"
    - ssh vagrant@test "docker rm $CONTAINER_NAME || true"
    - ssh vagrant@test docker run -d --rm --name $CONTAINER_NAME -p 8090:8080 $INTERNAL_DOCKER_REGISTRY/$CONTAINER_NAME:$CI_COMMIT_SHA
  environment:
    name: test
    url: http://test:8090/
  dependencies:
  - build:go
  only:
  - master
