version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: gitlab:5000/gorest:latest
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
        - node.labels.server_type==web
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet: